name       : networkx
version    : 2.2
release    : 6
source     :
    - https://github.com/networkx/networkx/archive/networkx-2.2.tar.gz : 74efce06507cdc2e506c6b7d485a18617adc3a7f355e2dc48ca71c83929bc679
license    : BSD-3-Clause
component  : programming.python
summary    : NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
description: |
    NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
builddeps  :
    - pkgconfig(gdal)
    - matplotlib
    - numpy
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - python-setuptools
    - pyyaml
    - scipy
rundeps    :
    - gdal
    - matplotlib
    - numpy
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - pyyaml
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
