name       : networkx
version    : '2.8'
release    : 14
source     :
    - https://github.com/networkx/networkx/archive/refs/tags/networkx-2.8.tar.gz : bfe855d24ee71d78fcc7e687465463da98f7cfef2ea25e906235f550cc7e59f7
license    : BSD-3-Clause
component  : programming.python
summary    : NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks
description: |
    NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
builddeps  :
    - pkgconfig(gdal)
    - matplotlib
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - pyyaml
    - scipy
rundeps    :
    - gdal
    - matplotlib
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - pyyaml
    - scipy
build      : |
    %python3_setup
install    : |
    %python3_install
