name       : networkx
version    : '2.1'
release    : 5
source     :
    - https://github.com/networkx/networkx/archive/networkx-2.1.tar.gz : 46aab610cdf15e680d944cafbf926a1d638f0cd2f1336b0f978b768a37d037f4
license    : BSD-3-Clause
component  : programming.python
summary    : NetworkX is a Python package for the creation, manipulation, and study
    of the structure, dynamics, and functions of complex networks.
description: |
    NetworkX is a Python package for the creation, manipulation, and study of the structure, dynamics, and functions of complex networks.
builddeps  :
    - pkgconfig(gdal)
    - matplotlib
    - numpy
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - python-setuptools
    - pyyaml
    - scipy
rundeps    :
    - gdal
    - matplotlib
    - numpy
    - pygraphviz
    - python-decorator
    - python-lxml
    - python-pandas
    - pyyaml
    - scipy
build      : |
    %python_setup
    %python3_setup
install    : |
    %python_install
    %python3_install
